//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FieldDocumentMaker.WPF.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FieldDocumentMaker.WPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /*! For license information please see bundle.js.LICENSE.txt */
        ///(()=&gt;{var t={4634:(t,e,n)=&gt;{&quot;use strict&quot;;function r(t){for(var e=arguments.length,n=Array(e&gt;1?e-1:0),r=1;r&lt;e;r++)n[r-1]=arguments[r];throw Error(&quot;[Immer] minified error nr: &quot;+t+(n.length?&quot; &quot;+n.map((function(t){return&quot;&apos;&quot;+t+&quot;&apos;&quot;})).join(&quot;,&quot;):&quot;&quot;)+&quot;. Find the full error at: https://bit.ly/3cXEKWf&quot;)}function i(t){return!!t&amp;&amp;!!t[q]}function o(t){return!!t&amp;&amp;(function(t){if(!t||&quot;object&quot;!=typeof t)return!1;var e=Object.getPrototypeOf(t);return!e||e===Obj [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string bundle {
            get {
                return ResourceManager.GetString("bundle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;es&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
        ///    &lt;meta charser=&apos;utf-8&apos;&gt;
        ///    &lt;title&gt;Field Document Maker&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body style=&quot;background-color: #666;&quot;&gt;
        ///    &lt;script type=&quot;text/javascript&quot;&gt;
        ///        (async () =&gt;
        ///        {      
        ///			await cefSharp.bindObjectAsync(&quot;bound&quot;);
        ///			alert(bound.repeat(&quot;hi &quot;, 5));
        ///})();
        ///    &lt;/script&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string HtmlPage {
            get {
                return ResourceManager.GetString("HtmlPage", resourceCulture);
            }
        }
    }
}
